name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options:
          - preview
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1"

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Prisma generate
        run: bunx prisma generate

      - name: Lint
        run: bun run lint

      - name: Tests d'intégration
        run: bun run test

      - name: Build Next.js
        run: bun run build
